server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /en/index.html;
    }

    location /en/ {
        try_files $uri $uri/ /en/index.html;
    }

    location /fr/ {
        try_files $uri $uri/ /fr/index.html;
    }
}
